# Generated by Django 6.0.7 on 2026-07-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
