# Generated by Django 6.0.7 on 2026-08-04 18:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0003_alter_topic_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Content"),
        ),
    ]
